export const projects = [
	{
		img: 'https://i.ibb.co/GW6trgw/Screenshot-464.png',
		title: 'Cult.fit Clone',
		des: 'A cloned website of cult.fit, that provides fresh food delivery service in India.',
		demo: '',
		live: 'https://earnest-jalebi-432f9b.netlify.app',
		gitHub: 'https://github.com/jk872001/Cult.fit-Clone',
		technologies: ['JavaScript,',"HTML," ,'CSS'],
	},
	{
		img: 'https://i.ibb.co/qxvZmT6/Screenshot-465.png',
		title: 'Rodan-Fields/Clone',
		des: 'Rodan+Fields is a multi-national marketing organization that sells skin-care products. It also provides personal consultations for individuals.',
		demo: '',
		live: 'https://jolly-dasik-c3acae.netlify.app',
		gitHub: 'https://github.com/Mitul-778/Rodan-Fields',
		technologies: ['JavaScript,',"HTML," ,'CSS'],
	},
	{
		img: 'https://i.ibb.co/YfPtLzx/Screenshot-466.png',
		title: 'Facebook UI',
		des: 'A UI similiar like facebook made in 2 days with dark and light theme option ',
		demo: '',
		live: 'https://glowing-cactus-8e4204.netlify.app/',
		gitHub: '',
		technologies: [ 'HTML,', 'CSS,', 'JavaScript,','React.js,',"MUI,"],
	},
	// {
		// 	img: 'https://camo.githubusercontent.com/b7f4aa8c34ddf776dd19b78dc3488456470a73e5026f48784e9e753601468802/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c62507030307771454537386c6f68584d372f67697068792e676966',
		// 	title: 'Clone of Fitness Blender',
		// 	des: 'This is a clone of the Fitness Blender website. The clone is complete with a Login page, Sign-in page, Shopping Cart, Wishlist and Calendar Scheduling feature. Following is the link to the clone of the website.',
		// 	demo: '',
		// 	live: 'https://anshusagar.github.io/FitnessBlender/',
		// 	gitHub: 'https://github.com/Anshusagar/FitnessBlender.git',
		// 	technologies: ['HTML', 'CSS', 'javaScript'],
		// },
		// {
			// 	img: 'https://github.com/mandarsatam/Mailchimp-Clone/blob/master/Snips/Screenshot%20(79).png?raw=true',
			// 	title: 'Mailchimp Clone',
			// 	des: 'This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.',
			// 	demo: '',
			// 	live: 'https://mandarsatam.github.io/Mailchimp-Clone/',
	// 	gitHub: 'https://github.com/mandarsatam/Mailchimp-Clone',
	// 	technologies: ['HTML', 'CSS', 'javaScript'],
	// },
	{
		img: 'https://i.ibb.co/q7pdCj0/Screenshot-467.png',
		title: 'CRUD Application ',
		des: 'An Application which performs the crud operations deployed on heroku',
		demo: '',
		live: 'https://manageapp.herokuapp.com', // deployed link
		gitHub: '',
		technologies: [ 'HTML,', 'CSS,', 'JavaScript,','React.js,','MUI'],
	},
];
